"""All numerical presentation derives from saved query/summary records."""
import json
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
from analyze import HERE, DATA, CFG, load_records


def interval(row, name, factor=1, digits=2):
    return f"{factor*row[name+'_mean']:.{digits}f} [{factor*row[name+'_ci_low']:.{digits}f}, {factor*row[name+'_ci_high']:.{digits}f}]"


def event(row, name):
    n=int(row['eligible_n']);c=int(row[name+'_count'])
    return f"{c}/{n} ({100*c/n:.1f}%)" if n else '0/0 (undefined)'


def option_table(frame):
    lines=['| Contrast | Field | Eligible / subgroup N | Lost: n/N (%) [95% CI, %] | Gained: n/N (%) | Unchanged options: n/N (%) | Mean lost [CI] | Mean gained [CI] |',
           '|---|---|---:|---|---|---|---|---|']
    for r in frame.to_dict('records'):
        lines.append(f"| {r['comparison']} | {r['field']} | {int(r['eligible_n'])}/{int(r['subgroup_total'])} | {event(r,'any_lost')} [{100*r['any_lost_ci_low']:.1f}, {100*r['any_lost_ci_high']:.1f}] | {event(r,'any_gained')} | {event(r,'unchanged_options')} | {interval(r,'n_lost')} | {interval(r,'n_gained')} |")
    return lines+['']


def figure(primary,membership):
    dest=HERE/'figures';dest.mkdir(exist_ok=True)
    p=primary.set_index('field').loc[['material','shape','color']]
    p.to_csv(dest/'option_coverage_plot_data.csv')
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'pdf.fonttype':42,'ps.fonttype':42})
    fig=plt.figure(figsize=(10.4,5.0),facecolor='white')
    gs=fig.add_gridspec(1,2,left=.12,right=.97,top=.68,bottom=.26,wspace=.62,width_ratios=[1,1.5])
    a=fig.add_subplot(gs[0]);b=fig.add_subplot(gs[1])
    base=membership[membership.comparison.eq('raw_C0_vs_C1')].iloc[0]
    fig.text(.03,.94,'Product substitution does not always remove recorded options',fontsize=14,weight='bold')
    fig.text(.03,.88,f"WANDS / BGE native / C0 source order vs C1 reversal / Top-20 / Exact judgments",fontsize=10,color='#384650')
    fig.text(.03,.80,f"{int(base['n'])} evaluation queries     |     {int(base.membership_changed)} changed relevant membership     |     {int(base.cancellation)} exact Recall cancellations",fontsize=11,weight='bold')
    y=np.arange(3)
    eligible=p.eligible_n.to_numpy();total=int(base.cancellation)
    a.barh(y,np.full(3,total),color='#e7ebee',height=.5)
    a.barh(y,eligible,color='#31688e',height=.5)
    for i,n in enumerate(eligible):a.text(n+1.8,i,f'{int(n)}/{total}',va='center',fontsize=10)
    a.set_yticks(y,['Material','Shape','Color']);a.invert_yaxis();a.set_xlim(0,total+1)
    a.set_xticks([0,20,40,60,total]);a.set_xlabel('Cancellation queries (count)')
    a.set_title('Strict metadata eligibility',loc='left',fontsize=11,pad=15,weight='bold')
    a.grid(axis='x',alpha=.15);a.set_axisbelow(True)
    for metric,color,offset,marker in [('any_lost','#b84734',-.13,'o'),('any_gained','#217a79',.13,'s')]:
        mean=100*p[metric+'_mean'].to_numpy();low=100*p[metric+'_ci_low'].to_numpy();high=100*p[metric+'_ci_high'].to_numpy()
        b.errorbar(mean,y+offset,xerr=np.vstack([mean-low,high-mean]),fmt=marker,color=color,capsize=3,markersize=6,lw=1.5)
    b.axvline(100,color='#777',ls='--',lw=1,zorder=0)
    b.set_yticks(y,[f"n={int(r.eligible_n)}; lost {int(r.any_lost_count)}/{int(r.eligible_n)}" for r in p.itertuples()])
    b.invert_yaxis();b.set_xlim(-4,104);b.set_xticks([0,25,50,75,100]);b.set_xlabel('Eligible queries with an option event (%)')
    b.set_title('Loss and gain on each eligible support',loc='left',fontsize=11,pad=15,weight='bold')
    b.grid(axis='x',alpha=.15)
    for ax in [a,b]:
        ax.spines[['top','right','left']].set_visible(False);ax.tick_params(axis='y',length=0)
    fig.legend(handles=[Line2D([0],[0],marker='o',color='#b84734',label='Any lost option'),Line2D([0],[0],marker='s',color='#217a79',label='Any gained option'),Line2D([0],[0],ls='--',color='#777',label='Product substitution: 100% by subgroup definition')],
               loc='lower center',bbox_to_anchor=(.5,.115),ncol=3,frameon=False,fontsize=9)
    fig.text(.03,.065,'Each field has a different complete-observation support; excluded queries are not zero-change observations.',fontsize=9,color='#384650')
    fig.text(.03,.027,'Unadjusted 95% query bootstrap intervals, 10,000 draws. All supports are tiny; [0,0] does not establish impossibility.',fontsize=9,color='#384650')
    fig.savefig(dest/'option_coverage.pdf');fig.savefig(dest/'option_coverage.png',dpi=180);plt.close(fig)


def latex(primary):
    lines=[r'% Generated by present.py from data/option_summary.csv; input into a booktabs-enabled document.',
           r'\begin{table*}[t]',r'\centering',r'\small',r'\begin{tabular}{@{}lrrrr@{}}',r'\toprule',
           r'Field & Eligible $n/N$ & \shortstack{Any loss: count (\%)\\{}[95\% CI]} & Mean lost [CI] & Mean gained [CI] \\',r'\midrule']
    for r in primary.to_dict('records'):
        n=int(r['eligible_n']);c=int(r['any_lost_count']);N=int(r['subgroup_total'])
        lines.append(f"{r['field'].capitalize()} & {n}/{N} & {c}/{n} ({100*c/n:.1f}\\%) [{100*r['any_lost_ci_low']:.1f}, {100*r['any_lost_ci_high']:.1f}] & {interval(r,'n_lost')} & {interval(r,'n_gained')} \\")
        lines[-1]+='\\'
    lines += [r'\bottomrule',r'\end{tabular}',
      r'\caption{Recorded options under exact Recall@20 cancellation (WANDS/BGE, C0 versus C1). $N=73$ of 308 evaluation queries; eligibility requires both Exact candidate sets nonempty and every product in their union to have a valid value for the field. Means include zero-change queries. Brackets are unadjusted 95\% percentile intervals from 10,000 query resamples (seed 20261007). Supports are tiny; a degenerate [0,0] interval is not evidence that an event is impossible.}',
      r'\label{tab:option-coverage-diagnostic}',r'\end{table*}']
    (HERE/'table_option_coverage.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')


def report(summary,membership):
    provenance=json.loads((DATA/'provenance_checks.json').read_text(encoding='utf-8'))
    manifest=json.loads((DATA/'input_manifest.json').read_text(encoding='utf-8'))
    coverage=pd.read_csv(DATA/'catalog_coverage.csv')
    primary=summary[summary.comparison.eq('raw_C0_vs_C1')]
    report=['# Recorded product-option coverage diagnostic', '', 'Exploratory post-hoc analysis, 7 October 2026. No training, new query generation, inference, retrieval rerun, manuscript edit, commit or push. All planned saved ranking contrasts are available. All new outputs are isolated in `option_coverage_20261007/`.', '',
      '## Finding and strength of evidence', '',
      'The original evaluation anchors reproduce: **308 eligible queries and 73 exact-cancellation queries**. Recorded option identities can change while per-query Exact Recall@20 stays exactly constant. However, strict metadata observation leaves only **4 material, 6 shape and 9 color cancellation queries**, so the event percentages do not estimate prevalence across all 73 cancellations. Material is a zero result (0/4 loss); shape shows 1/6 loss; color shows 7/9 loss, alongside 7/9 gains. Product substitution also leaves field option sets unchanged in 4/4, 3/6 and 1/9 respectively.', '',
      '**Recommended placement: appendix diagnostic, with one cautious RQ2 pointer after the cancellation results.** The evidence supports existence and concrete audited examples, but is too limited and selected by metadata availability for a broad main-text quantitative claim. A short RQ3 cross-reference can note that fixed canonical representations retain different recorded descriptors; it must retain the small-support and historical batch-execution qualifications. No attempt was made to maximize positive findings.', '',
      '## Provenance and exact support', '',
      f"Repository commit `{manifest['commit']}`; branch `{manifest['branch']}`. Full paths, byte counts, SHA-256 hashes, runtime versions and configuration are in `data/input_manifest.json`; additional text-input hashes are in `data/serialization_audit.json`. Pre-existing manuscript and tracked edits were preserved and hashed in `data/preexisting_state.json`.", '',
      f"The full WANDS catalog contains {provenance['catalog_size']:,} IDs. The frozen held-out split has {provenance['heldout_queries']} queries; {provenance['no_exact_heldout']} have no retained Exact judgments, leaving {provenance['eligible_queries']} and {provenance['highest_pairs']:,} Exact query-product pairs. The 96 development queries were not substituted. Raw-label cleaning exactly reproduces processed qrels: {provenance['raw_conflicting_qrel_pairs']} conflicting pairs excluded and {provenance['raw_duplicate_rows_removed']} remaining duplicate rows collapsed. Unjudged products are unknown, never called irrelevant.", '',
      'The raw inputs are the saved Phase II catalog-wide Top-50 parquet files, truncated to the original first 20 IDs. Canonical inputs are saved graded-revision Top-1000 NPZ files mapped through the validated catalog axis. All 11 conditions, 3,388 query-run records have unique complete Top-20 IDs, known catalog IDs, identical judged Top-20 ranks, and Recall/nDCG agreement with saved results. No target-only ranks are used. All seven raw serializations match the original parser and frozen shuffle seeds, byte-for-byte source hashes and catalog ordering. Both canonical text hashes also reproduce. Comparisons use C0, C1, C2s1–C2s5 (seeds 20260911–20260915) and pure full-entry `(casefold(entry), entry)` lexical ascending/descending, never historical template M2 or JSON key sorting.', '',
      'BGE is `BAAI/bge-base-en-v1.5`, revision `a5beb1e3e68b9ab74eb54cfd186867f64f240e1a`, native CLS pooling, 512-token cap, empty prefixes, FP16 model/FP32 pooling. The raw seven share encoder implementation v1; canonical ascending/descending share v3. Each within-family comparison uses the same saved query embeddings, catalog, judgments and tie rule. Ties use descending FP32 score then original catalog index (ascending product IDs in this catalog). Dense and hybrid are separate. Canonical hybrids reuse full-catalog BM25 and dense ranks with FP32 equal-weight RRF, constant 60; no truncated-list fusion is constructed here.', '',
      '**Execution limitation:** '+provenance['canonical_execution_caveat'], '',
      'Missing planned artifacts: **none**. The additional condition needed for a strictly identical-execution sorting contrast is absent: WANDS/BGE ascending and descending canonical product encodings/rankings with the same effective batch ceiling, and corresponding hybrid rankings. No invented filename or alternative experiment is substituted. The historical 48-to-16 addendum is hashed and retained in the provenance records.', '',
      '## Frozen extraction and catalog audit', '',
      '`extraction_spec_v1.json` was frozen and the full-catalog extraction audited before option results were computed. Only exact generic raw keys `material`, `shape`, `color` are mapped, one field per key. Frame/upholstery/base/top/primary/main/detail keys and finish are not harmonized into generic keys. The census retains every raw key so narrower mapping and unused coverage remain inspectable.', '',
      'Normalization is NFC, casefold, trim and whitespace collapse. Wood versus engineered wood, gray versus dark gray, and rectangle versus rectangular remain distinct. Pipe separates source entries; no within-value list delimiter is documented, so composite scalar strings (e.g. `microfiber / polyester`, `taupe , burnt orange`) remain single literal descriptors, not decomposed options. Distinct duplicate-key values are unknown; missing/unknown values and malformed entries also exclude the product-field. The specification gives explicit field-specific handling of `none`. No attributes are inferred from titles or generated by an LLM. These are recorded descriptor identities, not a harmonized physical ontology.', '',
      '| Field | Catalog products | Raw key present | Valid | Unknown | Missing key | Conflicting values | Unknown sentinel |', '|---|---:|---:|---:|---:|---:|---:|---:|']
    for r in coverage.to_dict('records'):
        report.append(f"| {r['field']} | {int(r['total_products'])} | {int(r['raw_key_present'])} | {int(r['valid'])} ({100*r['valid']/r['total_products']:.1f}%) | {int(r['unknown'])} | {int(r['missing_key'])} | {int(r['conflicting_values'])} | {int(r['unknown_value'])} |")
    report += ['', 'Reason counts can overlap. The deterministic hash sample contains 30 present-key records per field (90 total): 28/29/23 valid and 2/1/7 conflicting unknowns for material/shape/color. All 90 source-entry checks passed, with **zero extraction errors** and no mapping revisions. `data/attribute_audit.jsonl` preserves complete original attributes; `data/attribute_audit_review.json` records semantic decisions, including opaque color name `soda` retained literally. Every processed catalog attribute list also matches the raw `product_features` pipe split. This is a source-fidelity audit, not independent physical validation.', '',
      '## Estimands, eligibility and uncertainty', '',
      'For each query, A is Top-20 intersected with the query’s Exact judgments. Cancellation is `|A_before − A_after| = |A_after − A_before| > 0`, using integer sets before any metadata filtering. A query-field is eligible only if both A sets are nonempty and every product in their union has valid, unambiguous values. Eligibility is symmetric; zero-change observations stay in the denominator. Option loss means a descriptor is absent from every relevant after-product, not merely carried by a departing product. Option gain is defined symmetrically. Equal option counts can conceal changed identities.', '',
      'Each field and subgroup resamples whole eligible queries 10,000 times, NumPy PCG64 seed 20261007, and reports unadjusted 95% percentile intervals. Event rates and query-macro counts include zeros. These intervals condition on the eligible sample, fixed artifacts and frozen extraction; they omit annotation error, selection uncertainty and model uncertainty. Supports below 20 are flagged as tiny; every cancellation field support is tiny. Degenerate intervals, especially [0,0] for material, do not establish that events cannot occur. Intervals containing zero do not establish equivalence. Machine-readable summaries include gain, unchanged-set, set-change, size and net-change intervals, and degeneracy flags.', '',
      'Full-ranking nDCG@20 is secondary and uses direct WANDS gains Exact=3, Partial=1, Irrelevant=0 and all judged gains for IDCG. Unjudged candidates contribute zero gain only to this metric while retaining unknown relevance. Recall cancellation is not an nDCG equality criterion.', '',
      '## Membership and effectiveness: every comparison', '',
      'All contrasts use 308 queries. Recall values are percentages; signed deltas and their intervals are percentage points. Gains/losses always use the named before-to-after direction. Ascending is a directional reference, not ground truth.', '',
      '| Contrast | Changed membership | Unchanged membership | Cancellation | Changed, non-cancellation | Recall before -> after (%) | Delta Recall pp [CI] | Delta nDCG pp [CI] |', '|---|---:|---:|---:|---:|---|---|---|']
    for r in membership.to_dict('records'):
        report.append(f"| {r['comparison']} | {r['membership_changed']}/308 | {r['unchanged_membership']}/308 | {r['cancellation']}/308 | {r['changed_non_cancellation']}/308 | {100*r['recall_before_mean']:.3f} -> {100*r['recall_after_mean']:.3f} | {interval(r,'delta_recall',100,3)} | {interval(r,'delta_ndcg',100,3)} |")
    report += ['', 'Primary C0/C1 has 34 empty before-sets and 33 empty after-sets. Those field observations are ineligible, not zero changes. Exact cancellation reproduces 73/308; 121 have unchanged membership and 114 change membership without cancellation. `data/membership.jsonl` retains all queries, full relevant IDs, integer counts and both scores.', '',
      '## Primary field results', '', 'All field-eligible evaluation queries:', '']
    report += option_table(primary[primary.subgroup.eq('all')])
    report += ['Primary scientific subgroup: exact Recall cancellation. The n/N eligibility fractions are 4/73, 6/73 and 9/73; they are only 5.5%, 8.2% and 12.3% of the cancellation pool. Supports differ by field and are never pooled.', '']
    report += option_table(primary[primary.subgroup.eq('cancellation')])
    report += ['Color has equal mean lost and gained counts (1.44 each), yet 8/9 option sets change identity. Shape has three changed sets (1 loss event, 2 gain events) and three unchanged sets. Material has no changed option sets on four cancellation queries, despite product substitutions in all four. These positive, mixed and zero results are all retained.', '',
      '## Exclusions and metadata coverage', '',
      'Exclusions apply to the union of original relevant candidates, with no cancellation recomputation. The following reasons overlap and must not be added. `data/exclusion_summary.csv` also provides mutually exclusive reason combinations, which do sum to excluded query counts.', '',
      '| Subgroup | Field | Excluded | Missing key | Conflicting values | Unknown sentinel | Empty before | Empty after |', '|---|---|---:|---:|---:|---:|---:|---:|']
    exc=pd.read_csv(DATA/'exclusion_summary.csv')
    for r in primary.to_dict('records'):
        e=exc[exc.comparison.eq(r['comparison'])&exc.field.eq(r['field'])&exc.subgroup.eq(r['subgroup'])&exc.category.eq('overlapping_reason')].set_index('reasons')['n'].to_dict()
        report.append(f"| {r['subgroup']} | {r['field']} | {r['excluded_n']}/{r['subgroup_total']} | {e.get('missing_key',0)} | {e.get('conflicting_values',0)} | {e.get('unknown_value',0)} | {e.get('empty_before',0)} | {e.get('empty_after',0)} |")
    cov=pd.read_csv(DATA/'coverage_summary.csv')
    report += ['', 'Coverage below is restricted to excluded primary query-fields. Candidate occurrences are query-specific (a product can recur across queries); macro fractions average nonempty query sets, and empty sets are reported separately.', '',
      '| Subgroup | Field | Setting | Excluded queries | With missing candidates | Known/total candidate occurrences | Known fraction micro | Known fraction macro |', '|---|---|---|---:|---:|---:|---:|---:|']
    for r in cov[cov.comparison.eq('raw_C0_vs_C1')&cov.population.eq('excluded')].to_dict('records'):
        report.append(f"| {r['subgroup']} | {r['field']} | {r['setting']} | {r['query_n']} | {r['queries_with_missing']} | {r['known_occurrences']}/{r['candidate_occurrences']} | {100*r['known_fraction_micro']:.1f}% | {100*r['known_fraction_query_macro']:.1f}% |")
    report += ['', 'Per-query missing IDs/reasons and before/after known fractions are retained in `data/query_fields.jsonl` and `data/exclusions.jsonl`. Observed descriptor arrays in incomplete records are descriptive coverage diagnostics only; they are not verified disappearance results. No incomplete-record loss percentage is presented. No combined “any field” percentage is computed on shifting supports.', '',
      '## Five-shuffle robustness', '', 'Each row has its own cancellation subgroup and eligible denominator. The overlapping query groups are not independent samples and are not summed.', '']
    raw=summary[summary.comparison.str.contains('C2s')]
    report+=option_table(raw[raw.subgroup.eq('cancellation')])
    report += ['The color loss pattern occurs in every shuffle contrast (4/8 to 8/8), but the supports remain only 7–11 queries and are selected differently. Material loss ranges 0–2 events and shape loss 0–3; the reversal material zero does not generalize to every shuffle. These results support a recurring descriptive phenomenon, not stable population rates or consistent benefits/harms.', '',
      'For completeness, all field-eligible evaluation-query results (including unchanged membership and non-cancellation queries) are:', '']
    report+=option_table(raw[raw.subgroup.eq('all')])
    report += ['Cross-contrast bootstrap resamples whole query vectors on a fixed support complete and cancelling in all six raw contrasts. Common n is only 2 material, 2 shape and 4 color queries. Five-shuffle mean loss probabilities minus reversal are +0.20 [0.00, 0.40], -0.20 [-0.40, 0.00] and +0.15 [0.00, 0.45], respectively. These intervals are descriptive and too sparse to establish consistency or differences. Every individual contrast and the joint resampling support are saved in `data/joint_query_bootstrap.csv`; no query-contrast independence assumption is used.', '',
      '## Canonical-rule comparison', '',
      'All eligible queries (no equal-Recall restriction):', '']
    can=summary[summary.comparison.str.startswith('canonical')]
    report+=option_table(can[can.subgroup.eq('all')])
    report += ['Canonical exact-cancellation subgroups, reported separately:', '']
    report+=option_table(can[can.subgroup.eq('cancellation')])
    report += ['Dense ascending versus descending changes relevant membership in 188/308 queries (65 cancellations). Overall strict supports are 21 material, 38 shape and 34 color queries: losses occur in 1/21, 3/38 and 9/34, with gains in 2/21, 4/38 and 9/34. Descending-minus-ascending Recall@20 is +0.203 pp [-0.676, +1.156]; the interval does not establish equivalence.', '',
      'Hybrid ascending versus descending changes relevant membership in 164/308 queries (66 cancellations). Overall strict supports are 23/37/34: losses occur in 0/23, 0/37 and 5/34, gains in 1/23, 2/37 and 6/34. Recall is 37.450% versus 38.373%, difference +0.923 pp [+0.190, +1.862]. This unadjusted interval is conditional on the saved artifacts and does not select a globally superior rule. The hybrid can show a mean Recall gain while some eligible queries lose recorded color descriptors.', '',
      'These are differences **between** fixed canonical representations. They do not show nonzero VI within either invariant method, nor isolate sorting from the documented batch-execution difference. Full field eligibility and zero-result rows are reported above rather than selecting favorable fields.', '',
      '## Verified cases and figure', '',
      '`CASE_AUDIT.md` verifies query 231 (“anti fatigue mat”): 5 products leave and 5 enter, Exact Recall remains 20/307 and nDCG@20 remains 1. Departing Anette Salon ID 19170 is the only relevant before-product recording `semi-circle`; no relevant after-product supplies that shape. Foam and black remain supplied. Material is complete and unchanged; color is ineligible due to one conflicting and one missing record. The full-list audit supports a recorded-shape disappearance; the two-row product example alone could not establish it.', '',
      'Additional cases are deterministically hash-selected: query 341 illustrates color loss; query 453 illustrates unchanged material options despite cancellation. They are field-specific and include every before/after relevant ID, full original attributes, ranks and extraction provenance in `data/cases.jsonl`. No category was replaced with a maximum-effect example.', '',
      '`table_option_coverage.tex` is an unintegrated manuscript-candidate table; `figures/option_coverage.pdf` is the vector figure with `option_coverage.png` preview. Both derive directly from `data/option_summary.csv`; the figure repeats every support denominator and separates metadata eligibility from eligible-query event rates.', '',
      '## Scope and unmeasured outcomes', '',
      'Supported claim: among the observed field-complete Exact candidate sets in these frozen WANDS/BGE retrieval artifacts, relevant-product substitution can change which literal recorded attribute descriptors are available despite exact Recall@20 cancellation. This happens for both losses and gains, and some substitutions leave descriptors unchanged. Different canonical fixed indexes also retain different descriptors. This is not total catalog diversity or an estimate over all relevant real-world products.', '',
      'Unmeasured: utility, user satisfaction, fairness, sales, downstream agent choices, physical truth/completeness, annotation error, unjudged relevance, combination-of-preference satisfaction, population representativeness, and model uncertainty. Sparse generic keys, conflicting entries, unharmonized synonyms and composite labels can all limit interpretation. Eligibility selection can correlate with product categories and retrieval outcomes; no missing-at-random claim is made. Do not interpret an appearing option as better or a disappearing option as harm.', '',
      '## Candidate results paragraph (computed evidence only)', '',
      'Suggested placement: RQ2, after cancellation results; retain the quantitative table in the appendix. The following English paragraph is 106 words:', '',
      '> A post-hoc WANDS/BGE diagnostic reproduced 73 exact Recall@20 cancellations among 308 queries. Requiring complete recorded metadata for both relevant candidate sets left only 4 material, 6 shape, and 9 color cases. Recorded options disappeared in 0/4, 1/6, and 7/9 cases, respectively, while option sets remained unchanged in 4/4, 3/6, and 1/9. Color gains also occurred in 7/9 cases; these shifts are not evidence of utility gains or losses. Color disappearance recurred across five saved shuffle contrasts, but small, varying supports limit generalization. Fixed canonical rules also retained different recorded options (RQ3). These exploratory results motivate an appendix diagnostic rather than a population-level claim about preference satisfaction.', '',
      'Suggested short RQ3 cross-reference: “The appendix option audit also finds descriptor differences between ascending and descending fixed canonical indexes, under limited metadata support and the recorded execution caveat; this does not contradict within-rule invariance.”', '',
      '## Reproduction and deliverables', '',
      'See `REPRODUCE.md` for exact commands, dependency versions, artifact paths and missing-artifact behavior. Focused tests cover loss redundancy, equal-count identity changes, deduplication, missing/conflicting exclusion, identical lists, before/after symmetry, integer cancellation, empty sets, unknown IDs and normalization. `qa/validation.json` verifies output identities, input hashes, exact table cells, counts, bootstrap behavior, and preservation of pre-existing files. `qa/visual_review.json` records PDF rendering inspection.', '']
    (HERE/'REPORT.md').write_text('\n'.join(report),encoding='utf-8')


def main():
    s=pd.read_csv(DATA/'option_summary.csv');m=pd.read_csv(DATA/'membership_summary.csv')
    primary=s[s.comparison.eq('raw_C0_vs_C1')&s.subgroup.eq('cancellation')]
    figure(primary,m);latex(primary);report(s,m)
    print('Wrote REPORT.md, LaTeX table, vector PDF and PNG preview from saved results.')


if __name__=='__main__':main()
